name: industrianacionaldesign
favicon: null
layout_spectrum: 0.85963
typography_spectrum: 0.67865
title: WELCOME TO THE REAL DESIGN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e9992'
    - '#5e432e'
    - '#0f1314'
    - '#ca937f'
    - '#c6dae0'
  brandStrength: 0.75
  lightness: 0.637309157056734
  saturation: 0.625
  rhythmicContrast: 0.32615517848171294
purpose: []
