name: industrianacionaldesign
favicon: null
layout_spectrum: 0
typography_spectrum: 0.15406
title: WELCOME TO THE REAL DESIGN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#abacb0'
    - '#4e4f51'
    - '#110907'
    - '#fac100'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
